### ISSUE TITLE
A newbie's Issue

### ISSUE THREAD

**Issue by asdaca0** [Hallupa/SimpleTradingSimulator#1] opened 2019-05-05 03:38 UTC
Hi ,  I really appreciate what you have done for us.
 I'm  very interested in it . but when I open the “src\TraderSimulator.sln" file with my Visual Studio 2017 , What I saw is "Unsupported" , what happened ? would you help me ? Thx

> Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - TraderSimulatorInstaller, "D:\Git_storage\Git_Tradesimulator\SimpleTradingSimulator-1.0.5\SimpleTradingSimulator-1.0.5\Src\TraderSimulatorInstaller\TraderSimulatorInstaller.vdproj"

No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - TraderSimulator, "D:\Git_storage\Git_Tradesimulator\SimpleTradingSimulator-1.0.5\SimpleTradingSimulator-1.0.5\Src\TraderSimulator.sln"
	 - , ""
	 - , ""
	 - , ""
	 - , ""
	 - , ""
	 - , ""

**Comment by Hallupa** [comment] 2019-05-06 16:33
Hi,

The vdproj project is the installer project - I think in Visual Studio 2017 it isn't enabled by default.

Can you try the following:
1.    Load Visual Studio .NET 2017
2.    Click on "Tools" -> Extension and Updates -> Online
3.    Type "Installer Project" on the search box
4.    Click on "Install" in Microsoft Visual Studio Installer Project
5.    Restart Visual Studio .NET and follow the instructions to install the extension

I've copied these steps from https://stackoverflow.com/questions/26028746/visual-studio-vdproj-is-incompatible but I think it should work.

Can you let me know if this solves it?

Thanks,
Oliver

**Comment by asdaca0** [comment] 2019-05-07 08:02
Hi,  Oliver.
Thx for your help! It works for my VS 2017. I  cant' get the  "Installer Project"  in  "Tools" -> Extension and Updates -> Online. So I downloaded it  from "marketplace.visualstudio.com" and installed it , that solved my problem. 
But there is another Issue when I  "Start" the  "debug"(Any CPU) ,I have 11 Errors , Could I trouble you to
help me ? 
`Severity	Code	Description	Project	File	Line	Suppression State
Error		The tag 'CustomAnnotation' does not exist in XML namespace 'http://schemas.abtsoftware.co.uk/scichart'. Line 1 Position 21.	TraderTools.Core.UI	D:\Git_storage\SimpleTradingSimulator\Src\TraderTools.Core.UI\Controls\BuyMarkerAnnotation.xaml	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error		The tag 'CustomAnnotation' does not exist in XML namespace 'http://schemas.abtsoftware.co.uk/scichart'. Line 3 Position 21.	TraderTools.Core.UI	D:\Git_storage\SimpleTradingSimulator\Src\TraderTools.Core.UI\Controls\SellMarkerAnnotation.xaml	3	

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Interactivity' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)	Library.UI	D:\Git_storage\SimpleTradingSimulator\Src\Library.UI\Behaviours\ListBoxSelectionBehavior.cs	6	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Behavior<>' could not be found (are you missing a using directive or an assembly reference?)	Library.UI	D:\Git_storage\SimpleTradingSimulator\Src\Library.UI\Behaviours\ListBoxSelectionBehavior.cs	10	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error		The tag 'BoolToVisibilityConverter' does not exist in XML namespace 'clr-namespace:Hallupa.Library.UI.Converters;assembly=Hallupa.Library.UI'. Line 12 Position 14.	TraderTools.Core.UI	D:\Git_storage\SimpleTradingSimulator\Src\TraderTools.Core.UI\Views\TradesResultsControl.xaml	12	

Severity	Code	Description	Project	File	Line	Suppression State
Error		The tag 'BoolToVisibilityConverter' does not exist in XML namespace 'clr-namespace:Hallupa.Library.UI.Converters;assembly=Hallupa.Library.UI'. Line 12 Position 14.	TraderTools.TradingSimulator	D:\Git_storage\SimpleTradingSimulator\Src\TraderTools.TraderSimulator\EditTradeWindow.xaml	12	

Severity	Code	Description	Project	File	Line	Suppression State
Error		The tag 'BindingProxy' does not exist in XML namespace 'clr-namespace:Hallupa.Library.UI;assembly=Hallupa.Library.UI'. Line 13 Position 14.	TraderTools.Core.UI	D:\Git_storage\SimpleTradingSimulator\Src\TraderTools.Core.UI\Views\TradeListControl.xaml	13	

Severity	Code	Description	Project	File	Line	Suppression State
Error		The tag 'BindingProxy' does not exist in XML namespace 'clr-namespace:Hallupa.Library.UI;assembly=Hallupa.Library.UI'. Line 16 Position 14.	TraderTools.Core.UI	D:\Git_storage\SimpleTradingSimulator\Src\TraderTools.Core.UI\DoubleChartView.xaml	16	

Severity	Code	Description	Project	File	Line	Suppression State
Error		The tag 'BindingProxy' does not exist in XML namespace 'clr-namespace:Hallupa.Library.UI;assembly=Hallupa.Library.UI'. Line 18 Position 14.	TraderTools.TradingSimulator	D:\Git_storage\SimpleTradingSimulator\Src\TraderTools.TraderSimulator\MainWindow.xaml	18	

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'ListBoxSelectionBehavior.OnAttached()': no suitable method found to override	Library.UI	D:\Git_storage\SimpleTradingSimulator\Src\Library.UI\Behaviours\ListBoxSelectionBehavior.cs	72	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'ListBoxSelectionBehavior.OnDetaching()': no suitable method found to override	Library.UI	D:\Git_storage\SimpleTradingSimulator\Src\Library.UI\Behaviours\ListBoxSelectionBehavior.cs	81	Active
`

**Comment by Hallupa** [comment] 2019-05-09 20:49
No problem, I'm happy to help
I've never tried to build it on any other laptop other than my own but I got hold of another and tried it. When I did try this I get the same errors. The issue is that some 3rd party libraries need to be installed.

To do this:
1. Install Expression Blend SDK from https://www.microsoft.com/en-gb/download/details.aspx?id=10801
2. Install SciChart 3.5.0.7128 from https://www.scichart.com/Downloads/v3.5/SciChart_v3.5.7128_Installer.zip

Then when building the x86 build configuration must be selected

Hopefully this should work, let me know how you get on

**Comment by asdaca0** [comment] 2019-05-10 01:45
You are so kind ,Mr Oliver.
I can't wait to have a try.
I will give feedback here. 
Have a good day!

**Comment by asdaca0** [comment] 2019-05-11 06:20
Hi，Oliver
It ‘s great ！It works 👍
You are right ，
`when building the x86 build configuration must be selected. `
I have tested AnyCpu and failed to start the project.
I'm glad I can go on 
Thx!

**Comment by Hallupa** [comment] 2019-05-12 16:46
That's good to hear, glad you got it working. Are you happy for me to close this issue?

**Comment by asdaca0** [comment] 2019-05-13 00:01
Yes,please.
THANK U VERY MUCH AGAIN & AGAIN!

**Comment by asdaca0** [comment] 2019-05-13 04:30
Hi，Oliver.
Here is a small question,
Which IDE will you suggest me,  to open this project,  
Blend  OR  Visual Studio 2017 ?

**Comment by Hallupa** [comment] 2019-05-13 11:26
I would recommend Visual Studio 2017 - I didn't use Blend when developing it

**Closed as completed** 2019-05-13 11:27 UTC
